version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  pg:
    image: postgres:16-alpine3.18
    env_file:
      - ".env"
    ports:
      - "54322:5432"

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg
